//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Store product.
    /// </summary>
    // *** Start programmer edit section *** (StoreProduct CustomAttributes)

    // *** End programmer edit section *** (StoreProduct CustomAttributes)
    [AutoAltered()]
    [Caption("ТоварНаСкладе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("StoreProductE", new string[] {
            "Amount as \'Количество\'",
            "Product as \'Товар\'",
            "Product.Name as \'\'"}, Hidden=new string[] {
            "Product.Name"})]
    [MasterViewDefineAttribute("StoreProductE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class StoreProduct : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.Shop2.Product fProduct;
        
        private IIS.Shop2.Storehouse fStorehouse;
        
        // *** Start programmer edit section *** (StoreProduct CustomMembers)

        // *** End programmer edit section *** (StoreProduct CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Amount CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Amount Get start)

                // *** End programmer edit section *** (StoreProduct.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (StoreProduct.Amount Get end)

                // *** End programmer edit section *** (StoreProduct.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Amount Set start)

                // *** End programmer edit section *** (StoreProduct.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (StoreProduct.Amount Set end)

                // *** End programmer edit section *** (StoreProduct.Amount Set end)
            }
        }
        
        /// <summary>
        /// Store product.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Product CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Product CustomAttributes)
        public virtual IIS.Shop2.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Product Get start)

                // *** End programmer edit section *** (StoreProduct.Product Get start)
                IIS.Shop2.Product result = this.fProduct;
                // *** Start programmer edit section *** (StoreProduct.Product Get end)

                // *** End programmer edit section *** (StoreProduct.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Product Set start)

                // *** End programmer edit section *** (StoreProduct.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (StoreProduct.Product Set end)

                // *** End programmer edit section *** (StoreProduct.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Shop2.Storehouse.
        /// </summary>
        // *** Start programmer edit section *** (StoreProduct.Storehouse CustomAttributes)

        // *** End programmer edit section *** (StoreProduct.Storehouse CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Shop2.Storehouse Storehouse
        {
            get
            {
                // *** Start programmer edit section *** (StoreProduct.Storehouse Get start)

                // *** End programmer edit section *** (StoreProduct.Storehouse Get start)
                IIS.Shop2.Storehouse result = this.fStorehouse;
                // *** Start programmer edit section *** (StoreProduct.Storehouse Get end)

                // *** End programmer edit section *** (StoreProduct.Storehouse Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StoreProduct.Storehouse Set start)

                // *** End programmer edit section *** (StoreProduct.Storehouse Set start)
                this.fStorehouse = value;
                // *** Start programmer edit section *** (StoreProduct.Storehouse Set end)

                // *** End programmer edit section *** (StoreProduct.Storehouse Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "StoreProductE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StoreProductE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StoreProductE", typeof(IIS.Shop2.StoreProduct));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of StoreProduct.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfStoreProduct CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfStoreProduct CustomAttributes)
    public class DetailArrayOfStoreProduct : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Shop2.DetailArrayOfStoreProduct members)

        // *** End programmer edit section *** (IIS.Shop2.DetailArrayOfStoreProduct members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type StoreProduct by index.
        /// </summary>
        /// <summary>
        /// Adds object with type StoreProduct.
        /// </summary>
        public DetailArrayOfStoreProduct(IIS.Shop2.Storehouse fStorehouse) : 
                base(typeof(StoreProduct), ((ICSSoft.STORMNET.DataObject)(fStorehouse)))
        {
        }
        
        public IIS.Shop2.StoreProduct this[int index]
        {
            get
            {
                return ((IIS.Shop2.StoreProduct)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Shop2.StoreProduct dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
